# Generated by Django 4.1.3 on 2023-01-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg_tb1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=50)),
                ('pn', models.IntegerField()),
                ('em', models.EmailField(max_length=254)),
                ('ps', models.CharField(max_length=8)),
                ('cps', models.CharField(max_length=8)),
                ('to', models.CharField(max_length=20)),
            ],
        ),
    ]
