# Generated by Django 4.1.3 on 2023-01-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tra_tb1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('te', models.CharField(max_length=15)),
                ('ti', models.FileField(upload_to='pictures')),
                ('tp', models.IntegerField()),
                ('tm', models.IntegerField()),
            ],
        ),
    ]
