# Generated by Django 4.1.3 on 2023-01-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_tra_tb1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tra_tb1',
            name='tp',
        ),
        migrations.AlterField(
            model_name='tra_tb1',
            name='tm',
            field=models.CharField(max_length=30),
        ),
    ]
