# Generated by Django 4.1.3 on 2023-01-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_tra_tb1_tp_alter_tra_tb1_tm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tra_tb1',
            name='tm',
        ),
        migrations.AddField(
            model_name='tra_tb1',
            name='bk',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
