# Generated by Django 4.1.3 on 2023-02-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_tra_tb1_tm_tra_tb1_bk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tra_tb1',
            name='bk',
        ),
    ]
