# Generated by Django 4.1.3 on 2023-02-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_remove_tra_tb1_bk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tra_tb1',
            old_name='ti',
            new_name='tm',
        ),
        migrations.RenameField(
            model_name='tra_tb1',
            old_name='te',
            new_name='tp',
        ),
    ]
