# Generated by Django 4.1.3 on 2023-02-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_rename_ti_tra_tb1_tm_rename_te_tra_tb1_tp'),
    ]

    operations = [
        migrations.CreateModel(
            name='trb_tb1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.CharField(max_length=15)),
                ('t', models.FileField(upload_to='pictures')),
            ],
        ),
    ]
